package com.sist.vo;

import lombok.Getter;
import lombok.Setter;

/*
SIDOEDU,LOCALEDU,LLOCAL,SCHOOLNO,SCHOOLNAME,SCHOOLCODE,SCHOOLTYPE,DAYANDNIGHT,GRADUATE_MALE,GRADUATE_FEMALE,GRADUATE_TOTAL,COLLEGE_MALE,COLLEGE_FEMALE,COLLEGE_TOTAL,COLLEGE_TOTAL_RATIO,HIRED_MALE,HIRED_FEMALE,HIRED_TOTAL,HIRED_TOTAL_RATIO,OTHER_MALE,OTHER_FEMALE,OTHER_TOTAL,HER_TOTAL_RATIO
 */
@Getter
@Setter
public class highSchool_GraduateVO {
	private String SIDOEDU,LOCALEDU,LLOCAL,SCHOOLNO,SCHOOLNAME,SCHOOLCODE,SCHOOLTYPE,DAYANDNIGHT,GRADUATE_MALE,GRADUATE_FEMALE,GRADUATE_TOTAL,COLLEGE_MALE,COLLEGE_FEMALE,COLLEGE_TOTAL,COLLEGE_TOTAL_RATIO,HIRED_MALE,HIRED_FEMALE,HIRED_TOTAL,HIRED_TOTAL_RATIO,OTHER_MALE,OTHER_FEMALE,OTHER_TOTAL,OTHER_TOTAL_RATIO;
}
